name: ​🐞 Bug
description: Report an issue to help us improve the project.
title: "[BUG] write a title here"
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Description
      description: A brief description of the issue or bug you are facing, also include what you tried and what didn't work.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false