export const topics = [
    "Array",
    "Backtracking",
    "Binary Indexed Tree",
    "Binary Search",
    "Binary Search Tree",
    "Bit Manipulation",
    "Brainteaser",
    "Breadth-first Search",
    "Depth-first Search",
    "Dequeue",
    "Design",
    "Divide and Conquer",
    "Dynamic Programming",
    "Geometry",
    "Graph",
    "Greedy",
    "Hash Table",
    "Heap",
    "Line Sweep",
    "Linked List",
    "Math",
    "Meet in the Middle",
    "Memoization",
    "Minimax",
    "OOP",
    "Ordered Map",
    "Queue",
    "Random",
    "Recursion",
    "Rejection Sampling",
    "Reservoir Sampling",
    "Rolling Hash",
    "Segment Tree",
    "Sliding Window",
    "Sort",
    "Stack",
    "String",
    "Suffix Array",
    "Topological Sort",
    "Tree",
    "Trie",
    "Two Pointers",
    "Union Find",
  ];
  
  export const companies = [
      "ByteDance",
      "TripleByte",
      "Startup",
      "ZScaler",
      "Google",
      "Leap Motion",
      "Booking.com",
      "Zillow",
      "Mathworks",
      "ServiceNow",
      "Yelp",
      "Booking",
      "Paypal",
      "Fleetx",
      "Swiggy",
      "Akamai",
      "Nagarro",
      "codeagon",
      "Indeed",
      "Pocket Gems",
      "Salesforce",
      "HRT",
      "Atlassian",
      "National Instruments",
      "Expedia",
      "tcs",
      "Lucid",
      "Dream11",
      "PayTM",
      "Adobe",
      "Qualcomm",
      "Square",
      "Hotstar",
      "LinkedIn",
      "Ajira",
      "Reddit",
      "Directi",
      "InMobi",
      "Bloomreach",
      "MakeMyTrip",
      "Cloudera",
      "Citadel",
      "BlackRock",
      "Nvidia",
      "Barclays",
      "Databricks",
      "Uber",
      "Yahoo",
      "Amazon",
      "Samsung",
      "Machine Zone",
      "Netsuite",
      "Cisco",
      "NetEase",
      "United Health Group",
      "Mercari",
      "Epic Systems",
      "Postmates",
      "DoorDash",
      "Microstrategy",
      "Arcesium",
      "Opendoor",
      "Capital One",
      "TSYS",
      "Blizzard",
      "JP Morgan",
      "DE Shaw",
      "Zalando",
      "Docusign",
      "Whole Foods Market",
      "Softwire",
      "GSN Games",
      "Zoom",
      "UiPath",
      "Netflix",
      "Coursera",
      "Trexquant",
      "Tesla",
      "Huwaei",
      "Tencent",
      "Garena",
      "Arista Networks",
      "Cashfree",
      "Akuna Capital",
      "Media.net",
      "Valve",
      "Apple",
      "Codenation",
      "Sumologic",
      "Point72",
      "Sumerge",
      "Duolingo",
      "IBM",
      "Dropbox",
      "Oracle",
      "Quora",
      "SAP",
      "Hulu",
      "Toptal",
      "Pure Storage",
      "Thumbtack",
      "Delivery Hero",
      "AppDynamics",
      "Vimeo",
      "C3.ai",
      "Splunk",
      "MindTickle",
      "JPMorgan",
      "Accolite",
      "Nutanix",
      "Poshmark",
      "Facebook",
      "Clutter",
      "NerdWallet",
      "AllinCall",
      "Coupang",
      "Roblox",
      "Audible",
      "Twitter",
      "Karat",
      "Box",
      "Redfin",
      "Wish",
      "Dunzo",
      "GoDaddy",
      "Optum",
      "endurance",
      "OT",
      "Intel",
      "Sapient",
      "Airbnb",
      "Pinterest",
      "Citrix",
      "Asana",
      "Nuro",
      "Virtu Financial",
      "Lendingkart",
      "Qualtrics",
      "Walmart Labs",
      "Airtel",
      "Rupeek",
      "IXL",
      "Unacademy",
      "Microsoft",
      "Brillio",
      "SoundHound",
      "Wayfair",
      "Twitch",
      "Alibaba",
      "Lyft",
      "Gilt Groupe",
      "CoderByte",
      "FactSet",
      "Flipkart",
      "Palantir Technologies",
      "Works Applications",
      "TripAdvisor",
      "Two Sigma",
      "Turvo",
      "C3 IoT",
      "Affirm",
      "Morgan Stanley",
      "Spotify",
      "MachineZone",
      "Bloomberg",
      "Alation",
      "Zenefits",
      "Traveloka",
      "Robinhood",
      "Huawei",
      "Sprinklr",
      "Snapchat",
      "Walmart",
      "Rubrik",
      "Yandex",
      "Activision",
      "MAQ Software",
      "edabit",
      "eBay",
      "DRW",
      "Pony.ai",
      "Houzz",
      "Intuit",
      "Goldman Sachs",
      "Jane Street",
      "LiveRamp",
      "peak6",
      "HeavyWater",
      "VMware",
      "DiDi",
      "American Express",
      "Twilio",
      "HBO",
      "Infosys",
      "APT Portfolio",
      "CureFit",
      "Grab",
      "Visa",
      "Kakao",
      "DJI"
  ]