# .github/workflows/supabase-activity-scheduler.yml

name: Supabase Activity Scheduler

on:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 every day
  workflow_dispatch:

jobs:
  send-http-request:
    runs-on: ubuntu-latest

    steps:
      - name: Send HTTP Request
        run: curl -X GET https://leetcode-journal.vercel.app/api/etc/supabase-activity-scheduler